language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly
    - php: 7.4snapshot

script:
  - phpize
  - ./configure
  - make
  - REPORT_EXIT_STATUS=1 TEST_PHP_ARGS="-q --show-diff" make test

#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/428fac7bd9f4b867c347
#    on_success: always
#    on_failure: always
#    on_start: always
