name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  all:
    name: PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        php: 
          - 8.1.26
          - 8.2.13
          - 8.3.0
          - 8.4.0beta5

    uses: ./.github/workflows/main-php-matrix.yml
    with:
      php: ${{ matrix.php }}
    secrets: inherit
