name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  all-linux:
    name: Linux - PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        php: 
          - 8.1.30
          - 8.2.25
          - 8.3.13
          - 8.4.0RC4

    uses: ./.github/workflows/main-php-matrix.yml
    with:
      php: ${{ matrix.php }}
    secrets: inherit

  all-windows:
    name: Windows - PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.1.30
            vs-crt: vs16
          - php: 8.2.25
            vs-crt: vs16
          - php: 8.3.13
            vs-crt: vs16
          - php: 8.40RC4
            vs-crt: vs17

    uses: ./.github/workflows/main-php-matrix-windows.yml
    with:
      php: ${{ matrix.php }}
      vs-crt: ${{ matrix.vs-crt }}
      build-type: ${{ matrix.build-type }}
    secrets: inherit
