name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Tests (PHP ${{ matrix.php }}, OPcache ${{ matrix.opcache }}, ZMM ${{ matrix.zend-alloc }}, JIT ${{ matrix.jit }})
    env:
      PHP_BUILD_REVISION: 5a3d184ed9b817ffe8e405a3475eca7652a9ec8c
    strategy:
      fail-fast: false
      matrix:
        php: [7.3.27, 7.4.15, 8.0.2]
        opcache: [0, 1]
        zend-alloc: [0, 1]
        jit: [0]
        include:
          - php: 8.0.2
            opcache: 1
            zend-alloc: 0
            jit: 1205
          - php: 8.0.2
            opcache: 1
            zend-alloc: 1
            jit: 1205

    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Restore PHP build cache
        uses: actions/cache@v2
        id: php-build-cache
        with:
          path: ${{ github.workspace }}/php 
          key: php--${{ matrix.php }}
          
      - name: Clone php-build repository
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: php-build/php-build
          ref: 5a3d184ed9b817ffe8e405a3475eca7652a9ec8c
          path: php-build

      - name: Compile PHP
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: |
          cd $GITHUB_WORKSPACE/php-build
          ./install-dependencies.sh
          PHP_BUILD_ZTS_ENABLE=on ./bin/php-build ${{ matrix.php }} $GITHUB_WORKSPACE/php

      - name: Compile extension
        run: |
          $GITHUB_WORKSPACE/php/bin/phpize
          ./configure --with-php-config=$GITHUB_WORKSPACE/php/bin/php-config
          make install

      - name: Generate php.ini
        run: |
          echo "extension=pthreads.so" > $GITHUB_WORKSPACE/php.ini
          if [[ "${{ matrix.opcache }}" == "1" ]]; then
            echo "Enabling OPcache"
            echo "zend_extension=opcache.so" >> $GITHUB_WORKSPACE/php.ini
            echo "opcache.enable=1" >> $GITHUB_WORKSPACE/php.ini
            echo "opcache.enable_cli=1" >> $GITHUB_WORKSPACE/php.ini
            echo "opcache.jit=${{ matrix.jit }}" >> $GITHUB_WORKSPACE/php.ini
            echo "opcache.jit_buffer_size=128M" >> $GITHUB_WORKSPACE/php.ini
          else
            echo "OPcache is not enabled for this run"
          fi

      - name: Run PHPT tests
        run: |
          USE_ZEND_ALLOC=${{ matrix.zend-alloc }} $GITHUB_WORKSPACE/php/bin/php ./run-tests.php -P -q --show-diff -n -c $GITHUB_WORKSPACE/php.ini
